#include "verilated.h"
#include "Vmux.h"  // Generated by Verilator
#include <iostream>
int main(int argc, char** argv, char** env) {
    // Initialize Verilator
    Verilated::commandArgs(argc, argv);

    // Instantiate Mux module
    Vmux* mux = new Vmux;

    mux->reg0 = 0x1000;
    mux->reg1 = 0x1000 + 1;
    mux->reg2 = 0x1000 + 2;
    mux->reg3 = 0x1000 + 3;
    mux->reg4 = 0x1000 + 4;
    mux->reg5 = 0x1000 + 5;
    mux->reg6 = 0x1000 + 6;
    mux->reg7 = 0x1000 + 7;

    // Test different select values
    for (int i = 0; i < 8; i++) {
        mux->mux_sel = i;  // Select one of the 10 inputs
        mux->eval();      // Evaluate the Mux

        // Print the mux output based on the selected input
        std::cout << "Select: " << i 
                  << " | Mux Output: " << std::hex << mux->out_data << std::endl;
    }

    // Cleanup
    mux->final();
    delete mux;

    return 0;
}
